use super::super::options::{OptionSpec, option_spec};

pub(crate) const CLAUDE_COMMANDS: &[&str] = &[
    "agents",
    "auth",
    "doctor",
    "install",
    "mcp",
    "plugin",
    "plugins",
    "setup-token",
    "update",
    "upgrade",
];
pub(crate) const CLAUDE_OPTIONS: &[&str] = &[
    "-c",
    "-d",
    "-h",
    "-p",
    "-r",
    "-v",
    "-w",
    "--help",
    "--add-dir",
    "--agent",
    "--continue",
    "--debug",
    "--debug-file",
    "--model",
    "--print",
    "--resume",
    "--worktree",
];
pub(crate) const CLAUDE_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["--add-dir", "--debug-file"], 1, true, false),
    option_spec(
        &["--agent", "--debug", "--model", "--resume", "--worktree"],
        1,
        false,
        false,
    ),
];

pub(crate) const CODEX_COMMANDS: &[&str] = &[
    "exec",
    "review",
    "login",
    "logout",
    "mcp",
    "mcp-server",
    "app-server",
    "app",
    "completion",
    "sandbox",
    "debug",
    "apply",
    "resume",
    "fork",
    "cloud",
    "features",
    "help",
];
pub(crate) const CODEX_OPTIONS: &[&str] = &[
    "-a",
    "-c",
    "-C",
    "-h",
    "-i",
    "-m",
    "-p",
    "-s",
    "-V",
    "--help",
    "--config",
    "--enable",
    "--disable",
    "--model",
    "--profile",
    "--sandbox",
    "--ask-for-approval",
    "--full-auto",
    "--search",
    "--cd",
    "--add-dir",
    "--image",
];
pub(crate) const CODEX_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(
        &["-C", "--cd", "--add-dir", "-i", "--image"],
        1,
        true,
        false,
    ),
    option_spec(
        &[
            "-a",
            "-c",
            "-m",
            "-p",
            "-s",
            "--config",
            "--enable",
            "--disable",
            "--model",
            "--profile",
            "--sandbox",
            "--ask-for-approval",
        ],
        1,
        false,
        false,
    ),
];
