use super::{
    branch_specs::{
        BRANCH_OPTIONS, CHECKOUT_OPTIONS, FETCH_OPTIONS, PULL_OPTIONS, PUSH_OPTIONS, SWITCH_OPTIONS,
    },
    common::{ADD_OPTIONS, COMMIT_OPTIONS, RESTORE_OPTIONS, STATUS_OPTIONS},
    history_specs::{
        CHERRY_PICK_OPTIONS, DIFF_OPTIONS, LOG_OPTIONS, MERGE_OPTIONS, REBASE_OPTIONS,
        RESET_OPTIONS, REVERT_OPTIONS, SHOW_OPTIONS,
    },
    repo_specs::{CLONE_OPTIONS, INIT_OPTIONS, STASH_OPTIONS, TAG_OPTIONS},
    types::{ArgKind, GitCommandSpec},
};

pub(in crate::repl::git_completion) const GIT_COMMANDS: &[GitCommandSpec] = &[
    GitCommandSpec {
        name: "status",
        summary: "show the working tree status",
        usage: "[--short] [--branch] [--] [<pathspec>...]",
        options: STATUS_OPTIONS,
        positionals: &[],
        trailing: Some(ArgKind::Pathspec),
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "add",
        summary: "stage file contents",
        usage: "[-A] [-p] [-u] [--] [<pathspec>...]",
        options: ADD_OPTIONS,
        positionals: &[],
        trailing: Some(ArgKind::Pathspec),
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "restore",
        summary: "restore files in the working tree or index",
        usage: "[--source <ref>] [--staged] [--worktree] [--] [<pathspec>...]",
        options: RESTORE_OPTIONS,
        positionals: &[],
        trailing: Some(ArgKind::Pathspec),
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "commit",
        summary: "record changes to the repository",
        usage: "[-m <message>] [-a] [--amend] [--fixup <commit>] [--] [<pathspec>...]",
        options: COMMIT_OPTIONS,
        positionals: &[],
        trailing: None,
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "switch",
        summary: "switch branches",
        usage: "[-c <branch>] [-C <branch>] [--detach] [<branch>]",
        options: SWITCH_OPTIONS,
        positionals: &[ArgKind::Branch],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "checkout",
        summary: "switch branches or restore files",
        usage: "[-b <branch>] [-B <branch>] [--detach] [<ref>] [--] [<pathspec>...]",
        options: CHECKOUT_OPTIONS,
        positionals: &[ArgKind::Ref],
        trailing: None,
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "branch",
        summary: "list, create, or delete branches",
        usage: "[-a|-r] [<branch>] [<start-point>]",
        options: BRANCH_OPTIONS,
        positionals: &[ArgKind::LocalBranch, ArgKind::Ref],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "push",
        summary: "update remote refs",
        usage: "[-u] [--force-with-lease] [<remote>] [<branch>]",
        options: PUSH_OPTIONS,
        positionals: &[ArgKind::Remote, ArgKind::Branch],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "pull",
        summary: "fetch from and integrate with another repository",
        usage: "[--rebase|--ff-only] [<remote>] [<remote/branch>]",
        options: PULL_OPTIONS,
        positionals: &[ArgKind::Remote, ArgKind::RemoteBranch],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "fetch",
        summary: "download refs from another repository",
        usage: "[--all] [--prune] [<remote>] [<remote/branch>]",
        options: FETCH_OPTIONS,
        positionals: &[ArgKind::Remote, ArgKind::RemoteBranch],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "merge",
        summary: "join development histories together",
        usage: "[--ff-only|--no-ff] [--squash] <ref>...",
        options: MERGE_OPTIONS,
        positionals: &[ArgKind::Ref],
        trailing: Some(ArgKind::Ref),
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "rebase",
        summary: "reapply commits on top of another base",
        usage: "[-i] [--onto <ref>] [<upstream>] [<branch>]",
        options: REBASE_OPTIONS,
        positionals: &[ArgKind::Ref, ArgKind::Branch],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "reset",
        summary: "reset current HEAD to the specified state",
        usage: "[--soft|--mixed|--hard] [<commit>] [--] [<pathspec>...]",
        options: RESET_OPTIONS,
        positionals: &[ArgKind::Commit],
        trailing: None,
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "revert",
        summary: "create commits that reverse earlier commits",
        usage: "[--no-edit] <commit>...",
        options: REVERT_OPTIONS,
        positionals: &[ArgKind::Commit],
        trailing: Some(ArgKind::Commit),
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "cherry-pick",
        summary: "apply the changes from existing commits",
        usage: "[-x] [--no-commit] <commit>...",
        options: CHERRY_PICK_OPTIONS,
        positionals: &[ArgKind::Commit],
        trailing: Some(ArgKind::Commit),
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "diff",
        summary: "show changes between commits, branches, or files",
        usage: "[--staged] [<ref>] [<ref>] [--] [<pathspec>...]",
        options: DIFF_OPTIONS,
        positionals: &[ArgKind::Ref, ArgKind::Ref],
        trailing: None,
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "show",
        summary: "show an object",
        usage: "[--stat] [--summary] [<object>]",
        options: SHOW_OPTIONS,
        positionals: &[ArgKind::Ref],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "log",
        summary: "show commit logs",
        usage: "[--oneline] [--graph] [-n <n>] [<ref>] [--] [<pathspec>...]",
        options: LOG_OPTIONS,
        positionals: &[ArgKind::Ref],
        trailing: None,
        after_double_dash: Some(ArgKind::Pathspec),
    },
    GitCommandSpec {
        name: "clone",
        summary: "clone a repository into a new directory",
        usage: "[--depth <n>] [-b <branch>] <url> [<path>]",
        options: CLONE_OPTIONS,
        positionals: &[ArgKind::Url, ArgKind::Path],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "init",
        summary: "create an empty Git repository",
        usage: "[--bare] [-b <branch>] [<path>]",
        options: INIT_OPTIONS,
        positionals: &[ArgKind::Path],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "tag",
        summary: "create, list, delete, or verify tags",
        usage: "[-a] [-d <tag>] [<tag>] [<commit>]",
        options: TAG_OPTIONS,
        positionals: &[ArgKind::Tag, ArgKind::Commit],
        trailing: None,
        after_double_dash: None,
    },
    GitCommandSpec {
        name: "stash",
        summary: "stash the changes in a dirty working directory",
        usage: "[push|pop|apply|list|show|drop] [<stash>]",
        options: STASH_OPTIONS,
        positionals: &[ArgKind::Stash],
        trailing: None,
        after_double_dash: None,
    },
];
