use phf::phf_map;

use crate::repl::contextual::options::{OptionSpec, option_spec};

pub(crate) const GIT_GLOBAL_OPTIONS: &[&str] = &[
    "--help",
    "--version",
    "--paginate",
    "--no-pager",
    "-C",
    "-c",
    "--git-dir",
    "--work-tree",
    "--namespace",
];
pub(crate) const GIT_SUBCOMMANDS: &[&str] = &[
    "add",
    "am",
    "archive",
    "bisect",
    "branch",
    "bundle",
    "checkout",
    "cherry-pick",
    "clean",
    "clone",
    "commit",
    "config",
    "describe",
    "diff",
    "fetch",
    "format-patch",
    "grep",
    "help",
    "init",
    "log",
    "merge",
    "mv",
    "pull",
    "push",
    "rebase",
    "reflog",
    "remote",
    "reset",
    "restore",
    "revert",
    "rm",
    "show",
    "shortlog",
    "stash",
    "status",
    "submodule",
    "switch",
    "tag",
    "worktree",
];
pub(crate) const GIT_REMOTE_SUBCOMMANDS: &[&str] = &[
    "add",
    "get-url",
    "prune",
    "remove",
    "rename",
    "set-branches",
    "set-head",
    "set-url",
    "show",
    "update",
];
pub(crate) static GIT_SUBCOMMAND_OPTIONS: phf::Map<&'static str, &'static [&'static str]> = phf_map! {
    "add" => &["-A", "-u", "-p", "--all", "--patch", "--update"],
    "branch" => &["-a", "-d", "-D", "-m", "-M", "--all", "--list"],
    "checkout" => &["-b", "-B", "--detach", "--ours", "--theirs", "--track", "--"],
    "commit" => &["-a", "-m", "--amend", "--fixup", "--no-edit"],
    "diff" => &["--cached", "--name-only", "--staged", "--stat", "--"],
    "fetch" => &["--all", "--prune", "--tags"],
    "log" => &["--graph", "--name-only", "--oneline", "--stat"],
    "merge" => &["--abort", "--continue", "--ff-only", "--no-ff"],
    "pull" => &["--ff-only", "--rebase", "--tags"],
    "push" => &["-f", "-u", "--force", "--set-upstream", "--tags"],
    "rebase" => &["-i", "--abort", "--continue", "--onto"],
    "reset" => &["--hard", "--mixed", "--soft"],
    "restore" => &["--source", "--staged", "--worktree", "--"],
    "show" => &["--name-only", "--stat"],
    "status" => &["-b", "-s", "--branch", "--short"],
    "switch" => &["-c", "-C", "--detach", "--guess", "--track"],
};

pub(crate) const GIT_GLOBAL_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["-C"], 1, true, true),
    option_spec(&["-c"], 1, false, false),
    option_spec(&["--git-dir", "--work-tree", "--namespace"], 1, true, false),
];
