use super::options::{OptionSpec, option_spec};

pub(crate) const CARGO_COMMANDS: &[&str] = &[
    "add",
    "bench",
    "build",
    "check",
    "clean",
    "clippy",
    "config",
    "doc",
    "fetch",
    "fix",
    "fmt",
    "help",
    "info",
    "init",
    "install",
    "locate-project",
    "login",
    "logout",
    "metadata",
    "new",
    "package",
    "publish",
    "remove",
    "run",
    "rustc",
    "rustdoc",
    "search",
    "test",
    "tree",
    "uninstall",
    "update",
    "vendor",
    "version",
];
pub(crate) const CARGO_OPTIONS: &[&str] = &[
    "--help",
    "--version",
    "--release",
    "--workspace",
    "--all-features",
    "--features",
    "-p",
    "--package",
    "--manifest-path",
    "--locked",
    "--offline",
    "-q",
    "--quiet",
    "-v",
    "--verbose",
];
pub(crate) const CARGO_OPTION_SPECS: &[OptionSpec] =
    &[option_spec(&["--manifest-path"], 1, true, false)];

pub(crate) const MOON_COMMANDS: &[&str] = &[
    "new",
    "build",
    "check",
    "run",
    "test",
    "clean",
    "fmt",
    "doc",
    "info",
    "bench",
    "add",
    "remove",
    "install",
    "tree",
    "fetch",
    "login",
    "register",
    "publish",
    "package",
    "update",
    "coverage",
    "generate-build-matrix",
    "upgrade",
    "shell-completion",
    "version",
    "help",
];
pub(crate) const MOON_OPTIONS: &[&str] = &[
    "-C",
    "--manifest-path",
    "--target-dir",
    "-q",
    "--quiet",
    "-v",
    "--verbose",
    "--trace",
    "--dry-run",
    "-Z",
    "--unstable-feature",
];
pub(crate) const MOON_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["-C", "--manifest-path", "--target-dir"], 1, true, false),
    option_spec(&["-Z", "--unstable-feature"], 1, false, false),
];

pub(crate) const GO_COMMANDS: &[&str] = &[
    "bug", "build", "clean", "doc", "env", "fix", "fmt", "generate", "get", "help", "install",
    "list", "mod", "run", "test", "tool", "version", "vet", "work",
];
pub(crate) const GO_HELP_TOPICS: &[&str] = &[
    "buildconstraint",
    "buildmode",
    "cache",
    "environment",
    "filetype",
    "go.mod",
    "gopath",
    "goproxy",
    "importpath",
    "modules",
    "module-auth",
    "packages",
    "private",
    "testflag",
    "testfunc",
    "vcs",
];
pub(crate) const GO_MOD_COMMANDS: &[&str] = &[
    "download", "edit", "graph", "init", "tidy", "vendor", "verify", "why",
];
pub(crate) const GO_WORK_COMMANDS: &[&str] = &["edit", "init", "sync", "use", "vendor"];

pub(crate) const ZIG_COMMANDS: &[&str] = &[
    "build",
    "build-exe",
    "build-lib",
    "build-obj",
    "test",
    "run",
    "fmt",
    "ast-check",
    "translate-c",
    "cc",
    "c++",
    "ar",
    "lib",
    "dlltool",
    "objcopy",
    "rc",
    "env",
    "help",
    "std",
    "libc",
    "targets",
    "version",
    "zen",
];

pub(crate) const NODE_COMMANDS: &[&str] = &["inspect"];
pub(crate) const NODE_OPTIONS: &[&str] = &[
    "-c",
    "-e",
    "-p",
    "--help",
    "--version",
    "--check",
    "--eval",
    "--print",
    "--watch",
    "--test",
    "--enable-source-maps",
    "--env-file",
    "--loader",
    "--inspect",
    "--inspect-brk",
];
pub(crate) const NODE_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["--env-file"], 1, true, false),
    option_spec(&["--loader"], 1, false, false),
];

pub(crate) const BUN_COMMANDS: &[&str] = &[
    "run", "test", "x", "repl", "exec", "install", "add", "remove", "update", "audit", "outdated",
    "link", "unlink", "publish", "patch", "pm", "info", "build", "init", "create", "upgrade",
];
pub(crate) const BUN_OPTIONS: &[&str] = &[
    "-c",
    "-e",
    "-h",
    "-i",
    "-p",
    "-r",
    "--help",
    "--watch",
    "--hot",
    "--smol",
    "--preload",
    "--inspect",
    "--install",
    "--no-install",
    "--env-file",
    "--cwd",
    "--config",
];
pub(crate) const BUN_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["--env-file", "--cwd", "--config"], 1, true, false),
    option_spec(&["--preload", "--inspect", "--install"], 1, false, false),
];

pub(crate) const PNPM_COMMANDS: &[&str] = &[
    "add",
    "install",
    "link",
    "remove",
    "unlink",
    "update",
    "audit",
    "list",
    "outdated",
    "why",
    "create",
    "dlx",
    "exec",
    "run",
    "config",
    "init",
    "publish",
    "self-update",
];
pub(crate) const PNPM_OPTIONS: &[&str] = &["--help", "-r", "--recursive", "--filter"];

pub(crate) const YARN_COMMANDS: &[&str] = &[
    "add",
    "config",
    "create",
    "dlx",
    "exec",
    "init",
    "install",
    "npm",
    "remove",
    "run",
    "set",
    "test",
    "up",
    "why",
    "workspaces",
];
pub(crate) const YARN_OPTIONS: &[&str] = &["-h", "--help", "--cwd", "--top-level", "--verbose"];
pub(crate) const YARN_OPTION_SPECS: &[OptionSpec] = &[option_spec(&["--cwd"], 1, true, false)];

pub(crate) const CLAUDE_COMMANDS: &[&str] = &[
    "agents",
    "auth",
    "doctor",
    "install",
    "mcp",
    "plugin",
    "plugins",
    "setup-token",
    "update",
    "upgrade",
];
pub(crate) const CLAUDE_OPTIONS: &[&str] = &[
    "-c",
    "-d",
    "-h",
    "-p",
    "-r",
    "-v",
    "-w",
    "--help",
    "--add-dir",
    "--agent",
    "--continue",
    "--debug",
    "--debug-file",
    "--model",
    "--print",
    "--resume",
    "--worktree",
];
pub(crate) const CLAUDE_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(&["--add-dir", "--debug-file"], 1, true, false),
    option_spec(
        &["--agent", "--debug", "--model", "--resume", "--worktree"],
        1,
        false,
        false,
    ),
];

pub(crate) const CODEX_COMMANDS: &[&str] = &[
    "exec",
    "review",
    "login",
    "logout",
    "mcp",
    "mcp-server",
    "app-server",
    "app",
    "completion",
    "sandbox",
    "debug",
    "apply",
    "resume",
    "fork",
    "cloud",
    "features",
    "help",
];
pub(crate) const CODEX_OPTIONS: &[&str] = &[
    "-a",
    "-c",
    "-C",
    "-h",
    "-i",
    "-m",
    "-p",
    "-s",
    "-V",
    "--help",
    "--config",
    "--enable",
    "--disable",
    "--model",
    "--profile",
    "--sandbox",
    "--ask-for-approval",
    "--full-auto",
    "--search",
    "--cd",
    "--add-dir",
    "--image",
];
pub(crate) const CODEX_OPTION_SPECS: &[OptionSpec] = &[
    option_spec(
        &["-C", "--cd", "--add-dir", "-i", "--image"],
        1,
        true,
        false,
    ),
    option_spec(
        &[
            "-a",
            "-c",
            "-m",
            "-p",
            "-s",
            "--config",
            "--enable",
            "--disable",
            "--model",
            "--profile",
            "--sandbox",
            "--ask-for-approval",
        ],
        1,
        false,
        false,
    ),
];
